//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.9-03/31/2009 04:14 PM(snajper)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 10:14:22 PM IST 
//


package org.jrestful.core.config.resource;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}resource-discovery"/>
 *         &lt;element ref="{}param-args"/>
 *         &lt;element ref="{}security"/>
 *         &lt;element ref="{}context"/>
 *         &lt;element ref="{}pre"/>
 *         &lt;element ref="{}post"/>
 *         &lt;element ref="{}result"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resourceDiscovery",
    "paramArgs",
    "security",
    "context",
    "pre",
    "post",
    "result"
})
@XmlRootElement(name = "extension")
public class Extension {

    @XmlElement(name = "resource-discovery", required = true)
    protected ResourceDiscovery resourceDiscovery;
    @XmlElement(name = "param-args", required = true)
    protected ParamArgs paramArgs;
    @XmlElement(required = true)
    protected Security security;
    @XmlElement(required = true)
    protected Context context;
    @XmlElement(required = true)
    protected Pre pre;
    @XmlElement(required = true)
    protected Post post;
    @XmlElement(required = true)
    protected Result result;

    /**
     * Gets the value of the resourceDiscovery property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceDiscovery }
     *     
     */
    public ResourceDiscovery getResourceDiscovery() {
        return resourceDiscovery;
    }

    /**
     * Sets the value of the resourceDiscovery property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceDiscovery }
     *     
     */
    public void setResourceDiscovery(ResourceDiscovery value) {
        this.resourceDiscovery = value;
    }

    /**
     * Gets the value of the paramArgs property.
     * 
     * @return
     *     possible object is
     *     {@link ParamArgs }
     *     
     */
    public ParamArgs getParamArgs() {
        return paramArgs;
    }

    /**
     * Sets the value of the paramArgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParamArgs }
     *     
     */
    public void setParamArgs(ParamArgs value) {
        this.paramArgs = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link Security }
     *     
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setSecurity(Security value) {
        this.security = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link Context }
     *     
     */
    public Context getContext() {
        return context;
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link Context }
     *     
     */
    public void setContext(Context value) {
        this.context = value;
    }

    /**
     * Gets the value of the pre property.
     * 
     * @return
     *     possible object is
     *     {@link Pre }
     *     
     */
    public Pre getPre() {
        return pre;
    }

    /**
     * Sets the value of the pre property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pre }
     *     
     */
    public void setPre(Pre value) {
        this.pre = value;
    }

    /**
     * Gets the value of the post property.
     * 
     * @return
     *     possible object is
     *     {@link Post }
     *     
     */
    public Post getPost() {
        return post;
    }

    /**
     * Sets the value of the post property.
     * 
     * @param value
     *     allowed object is
     *     {@link Post }
     *     
     */
    public void setPost(Post value) {
        this.post = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Result }
     *     
     */
    public Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Result }
     *     
     */
    public void setResult(Result value) {
        this.result = value;
    }

}
