//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.09.05 at 08:56:55 PM IST 
//


package org.jrestful.core.config;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.jrestful.core.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.jrestful.core.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Servicedescribe }
     * 
     */
    public Servicedescribe createServicedescribe() {
        return new Servicedescribe();
    }

    /**
     * Create an instance of {@link Include }
     * 
     */
    public Include createInclude() {
        return new Include();
    }

    /**
     * Create an instance of {@link Jrestful }
     * 
     */
    public Jrestful createJrestful() {
        return new Jrestful();
    }

    /**
     * Create an instance of {@link Methodmap }
     * 
     */
    public Methodmap createMethodmap() {
        return new Methodmap();
    }

    /**
     * Create an instance of {@link Paramprocessor }
     * 
     */
    public Paramprocessor createParamprocessor() {
        return new Paramprocessor();
    }

    /**
     * Create an instance of {@link Method }
     * 
     */
    public Method createMethod() {
        return new Method();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

}
